### ISSUE TITLE
restore old config dir doesn't work with managed vhosts

### ISSUE THREAD

**Issue by vdloo** [ByteInternet/nginx_config_reloader#32]
```
failed: [83.217.91.187] => {"changed": true, "cmd": ["/usr/bin/nginx_config_reloader"], "delta": "0:00:00.403567", "end": "2019-12-02 14:08:54.342280", "rc": 1, "start": "2019-12-02 14:08:53.938713", "warnings": []}
stderr: 2019-12-02 14:08:54,085 nginx_config_reloader INFO     /data/web/nginx
2019-12-02 14:08:54,104 nginx_config_reloader INFO     Failed fixing permissions on watched directory
2019-12-02 14:08:54,315 nginx_config_reloader INFO     Config check failed
Traceback (most recent call last):
File "/usr/bin/nginx_config_reloader", line 9, in <module>
load_entry_point('nginx-config-reloader==20190731.120623', 'console_scripts', 'nginx_config_reloader')()
File "/usr/lib/python2.7/dist-packages/nginx_config_reloader/__init__.py", line 387, in main
dir_to_watch=args.watchdir
File "/usr/lib/python2.7/dist-packages/nginx_config_reloader/__init__.py", line 223, in apply_new_config
self.restore_old_custom_config_dir()
File "/usr/lib/python2.7/dist-packages/nginx_config_reloader/__init__.py", line 256, in restore_old_custom_config_dir
shutil.rmtree(CUSTOM_CONFIG_DIR)
File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
onerror(os.rmdir, path, sys.exc_info())
File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/etc/nginx/app'
FATAL: all hosts have already failed -- aborting
```

**Comment by vdloo** [comment]
fixed since then
